language: node_js
node_js:
  - '10.13.0'
dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
cache:
  directories:
    - node_modules
branches:
  only: [master]
matrix:
  include:
    - env: TASK=test
      script: npm test
    - env: TASK=lint
      script: npm run lint
    - env: TASK=fossa # nice label for UI
      before_script:
        - curl -H 'Cache-Control:no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | BINDIR=$(pwd) bash
      script:
        - ./fossa init
        - ./fossa analyze
        - ./fossa test
  allow_failures:
    - env: TASK=fossa
